#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Usage: `basename $0` domain-name"
  echo -e "Example: ./`basename $0` www.example.com"
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
  exit 1
fi

source "${SCRIPT_DIR}/config/constants"

declare -r DOMAIN_NAME=$1

dig @127.0.0.1 -p${DNS_PORT} ${DOMAIN_NAME}