#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Usage: `basename $0`"
  echo -e "Example: ./`basename $0`"
}

if [[ "$1" =~ ^-h$ || "$1" =~ ^--help$ ]]; then
  usage
  exit 1
fi

source "${SCRIPT_DIR}/config"
cd "${SCRIPT_DIR}"

#   -v "$(pwd)/${HTDOCS_DIR}:/htdocs" \
# mkdir -p "${HTDOCS_DIR}"
docker run -d --name "${CONTAINER_NAME}" \
  -p "${DNS_PORT}:${DNS_PORT}/udp" \
  -p "${API_PORT}:${API_PORT}" \
  -v "${DATA_DIR}:/app/data" \
  -v "${TRASH_DIR}:/app/trash" \
  --user $(id -u):$(id -g) \
  --env ROOT_DOMAIN_NAME=${ROOT_DOMAIN_NAME} \
  "${IMAGE_NAME}:${IMAGE_TAG}"

  docker logs "${CONTAINER_NAME}"